import { Download, FileText, FileJson, Share2 } from "lucide-react";
import { useTheme } from "../contexts/ThemeContext";
import { exportToCSV, exportToJSON, generateReport } from "../utils/exportData";
import { useToast } from "../contexts/ToastContext";

const ExportData = ({ appliances = [], bills = [], metrics = {} }) => {
  const { darkMode } = useTheme();
  const { success } = useToast();

  const handleExportCSV = () => {
    if (appliances.length === 0 && bills.length === 0) {
      return;
    }

    const data = [];
    
    // Export appliances
    if (appliances.length > 0) {
      appliances.forEach(a => {
        data.push({
          Type: "Appliance",
          Name: a.name,
          Wattage: a.wattage,
          "Hours/Day": a.hours,
          "Daily Energy (kWh)": a.energy,
        });
      });
    }

    // Export bills
    if (bills.length > 0) {
      bills.forEach(b => {
        data.push({
          Type: "Bill",
          Month: b.month || b.monthName,
          Units: b.units || "",
          Amount: b.amount || "",
        });
      });
    }

    exportToCSV(data, "ecovolt-data");
    success("Data exported to CSV successfully!");
  };

  const handleExportJSON = () => {
    const report = generateReport(appliances, bills, metrics);
    exportToJSON(report, "ecovolt-report");
    success("Report exported to JSON successfully!");
  };

  const handleShareReport = async () => {
    const report = generateReport(appliances, bills, metrics);
    const reportText = `📊 EcoVolt 🌱 Report\n\n` +
      `💡 Appliances: ${report.summary.totalAppliances}\n` +
      `📄 Bills Tracked: ${report.summary.totalBills}\n` +
      `⚡ Monthly Consumption: ${report.summary.estimatedMonthlyConsumption.toFixed(1)} kWh\n` +
      `💰 Estimated Bill: Rs ${report.summary.estimatedMonthlyBill}\n` +
      `🌍 Potential Savings: ${report.summary.potentialSavings} kWh/month\n\n` +
      `Generated by EcoVolt 🌱 – Powering a Greener Pakistan`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: "EcoVolt 🌱 Report",
          text: reportText,
        });
        success("Report shared successfully!");
      } catch (err) {
        // User cancelled or error
      }
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(reportText).then(() => {
        success("Report copied to clipboard!");
      });
    }
  };

  const hasData = appliances.length > 0 || bills.length > 0;

  if (!hasData) {
    return null;
  }

  return (
    <div
      className={`rounded-xl p-4 border ${
        darkMode
          ? "bg-gray-900 border-gray-700"
          : "bg-white border-gray-200"
      }`}
    >
      <div className="flex items-center gap-2 mb-3">
        <Download className={`w-5 h-5 ${darkMode ? "text-green-400" : "text-green-600"}`} />
        <h3
          className={`font-semibold ${
            darkMode ? "text-gray-200" : "text-gray-900"
          }`}
        >
          Export & Share Data
        </h3>
      </div>
      <div className="flex flex-col sm:flex-row flex-wrap gap-2">
        <button
          onClick={handleExportCSV}
          className={`flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition min-h-[44px] ${
            darkMode
              ? "bg-green-600 hover:bg-green-700 text-white"
              : "bg-green-600 hover:bg-green-700 text-white"
          }`}
        >
          <FileText className="w-4 h-4" />
          <span>Export CSV</span>
        </button>
        <button
          onClick={handleExportJSON}
          className={`flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition min-h-[44px] ${
            darkMode
              ? "bg-blue-600 hover:bg-blue-700 text-white"
              : "bg-blue-600 hover:bg-blue-700 text-white"
          }`}
        >
          <FileJson className="w-4 h-4" />
          <span>Export JSON</span>
        </button>
        <button
          onClick={handleShareReport}
          className={`flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition min-h-[44px] ${
            darkMode
              ? "bg-purple-600 hover:bg-purple-700 text-white"
              : "bg-purple-600 hover:bg-purple-700 text-white"
          }`}
        >
          <Share2 className="w-4 h-4" />
          <span>Share Report</span>
        </button>
      </div>
    </div>
  );
};

export default ExportData;
